Fix PyO3 0.28.3 compatibility: add from_py_object to #[pyclass]
PyO3 0.28.3 introduced a breaking change that deprecates automatic FromPyObject 
implementation for #[pyclass] types that implement Clone. This fix adds the 
from_py_object attribute to opt-in to the previous behavior.

Fixes compilation error:
  error: use of deprecated associated constant `HasAutomaticFromPyObject::<true>::MSG`
  The `FromPyObject` implementation for `#[pyclass]` types which implement `Clone` 
  is changing to an opt-in option. Use `#[pyclass(from_py_object)]` to opt-in.